/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {BlogAuthorProps} from "../blog-author/BlogAuthorProps";

/**
 * The icon name for the social link
 */
export type Icon = string;
/**
 * The href for the social link
 */
export type Href = string;
/**
 * The title for the social link
 */
export type Title = string;
/**
 * The social sharing links for the blog post
 */
export type SocialSharing = {
  icon: Icon;
  href: Href;
  title: Title;
}[];
/**
 * The reading time for the blog post
 */
export type ReadingTime = string;
/**
 * The date when the blog post was published
 */
export type PublishedDate = string;

/**
 * Meta info for a singular blog entry
 */
export interface BlogAsideProps {
  /**
   * Referenced component BlogAuthorProps
   */
  author: BlogAuthorProps;
  socialSharing?: SocialSharing;
  readingTime?: ReadingTime;
  date: PublishedDate;
  className?: string;
}
