/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Headline for the FAQ section
 */
export type Headline = string;
/**
 * Introductory text for the FAQ section
 */
export type Intro = string;
/**
 * The questions and answers in the FAQ section
 *
 * @minItems 1
 */
export type Questions = [
  {
    question: Question;
    answer: Answer;
    [k: string]: unknown;
  },
  ...{
    question: Question;
    answer: Answer;
    [k: string]: unknown;
  }[]
];
/**
 * The question
 */
export type Question = string;
/**
 * The answer to the question
 */
export type Answer = string;
/**
 * The layout variant for the FAQ section
 */
export type Variant = "default" | "accordion" | "dropdown";
/**
 * The alignment of the text
 */
export type Alignment = "left" | "center" | "right";

/**
 * Component used to display a FAQ section
 */
export interface FAQProps {
  headline?: Headline;
  intro?: Intro;
  questions: Questions;
  variant?: Variant;
  alignment?: Alignment;
  [k: string]: unknown;
}
