/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Toggle visible layout tiles
 */
export type LayoutToggle = boolean;
/**
 * Toggle Invert
 */
export type InvertToggle = boolean;
/**
 * Toggle Invert
 */
export type InvertToggle1 = boolean;

export interface SectionControlsProps {
  layoutToggle?: LayoutToggle;
  themeSwitch?: InvertToggle;
  invertToggle?: InvertToggle1;
}
