/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Name of the tag entry
 */
export type Entry = string;

/**
 * Tag given to a blog post
 */
export interface BlogTagProps {
  entry: Entry;
}
