/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Text content to display beside the image
 */
export type Text = string;
/**
 * URL of the image to display
 */
export type ImageSource = string;
/**
 * Alt text of the image
 */
export type AltText = string;
/**
 * Position of the image relative to the text
 */
export type Layout = "above" | "below" | "beside-right" | "beside-left";

/**
 * Component used to display an image beside or above/below a text block
 */
export interface ImageTextProps {
  text: Text;
  image: {
    src?: ImageSource;
    alt?: AltText;
  };
  layout: Layout;
}
