/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Headline for the visual
 */
export type Headline = string;
/**
 * Subheadline below the module headline
 */
export type ModuleSubheadline = string;
/**
 * Info text for the module element
 */
export type ModuleText = string;
/**
 * Info text for the module element
 */
export type TileImage = string;
/**
 * Toggle wether the CTA is displayed or not
 */
export type CTAToggle = boolean;
/**
 * Text content to display inside the button
 */
export type Label = string;
/**
 * Target that should be linked, makes the button behave like a link semantically
 */
export type Target = string;
/**
 * Choose an icon
 */
export type Icon = string;
/**
 * Background color for the whole element
 */
export type BackgroundColor = string;
/**
 * Overwrite the color to use for the text content
 */
export type TextColor = string;

export interface MosaicProps {
  tiles?: {
    headline?: Headline;
    sub?: ModuleSubheadline;
    text?: ModuleText;
    image?: TileImage;
    cta?: {
      toggle?: CTAToggle;
      label?: Label;
      target?: Target;
      icon?: Icon;
    };
    backgroundColor?: BackgroundColor;
    textColor?: TextColor;
    [k: string]: unknown;
  }[];
}
