/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Layout of the mosaic component
 */
export type Layout = "alternate" | "textLeft" | "textRight";
/**
 * Make the headlines larger
 */
export type LargeHeadlines = boolean;
/**
 * Headline for the visual
 */
export type Headline = string;
/**
 * Subheadline below the module headline
 */
export type ModuleSubheadline = string;
/**
 * Info text for the module element
 */
export type ModuleText = string;
/**
 * Info text for the module element
 */
export type TileImage = string;
/**
 * Toggle wether the Button is displayed or not
 */
export type ButtonToggle = boolean;
/**
 * Text content to display inside the button
 */
export type Label = string;
/**
 * Target that should be linked, makes the button behave like a link semantically
 */
export type Target = string;
/**
 * Choose an icon
 */
export type Icon = string;
/**
 * Background color for the whole element
 */
export type BackgroundColor = string;
/**
 * Overwrite the color to use for the text content
 */
export type TextColor = string;

export interface MosaicProps {
  layout?: Layout;
  largeHeadlines?: LargeHeadlines;
  tiles?: {
    headline?: Headline;
    sub?: ModuleSubheadline;
    text?: ModuleText;
    image?: TileImage;
    button?: {
      toggle?: ButtonToggle;
      label?: Label;
      target?: Target;
      icon?: Icon;
    };
    backgroundColor?: BackgroundColor;
    textColor?: TextColor;
  }[];
}
