/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Headline for the module element
 */
export type ModuleHeadline = string;
/**
 * Make the headline larger
 */
export type LargeHeadline = boolean;
/**
 * Subheadline below the module headline
 */
export type ModuleSubheadline = string;
/**
 * Info text for the module element
 */
export type ModuleText = string;
/**
 * Choose the layout for the component
 */
export type Layout = "textLeft" | "imageLeft";
/**
 * Give the component padding
 */
export type Padding = boolean;
/**
 * Label for the Call to action
 */
export type Label = string;
/**
 * Target for the Call to action
 */
export type Target = string;
/**
 * Choose an icon
 */
export type Icon = string;
/**
 * Add Call to actions to the end of the section
 */
export type CallToActions = {
  label: Label;
  target: Target;
  icon?: Icon;
}[];
/**
 * Image source to use
 */
export type ImageSource = string;
/**
 * Select an aspect ratio to use for cropping and displaying the image
 */
export type ImageAspectRatio = "4:3" | "3:2" | "16:9" | "1:1" | "none";
/**
 * Image description
 */
export type AltText = string;
/**
 * Choose the alginment of the text
 */
export type TextAlignment = "left" | "center";

export interface ImageStoryProps {
  headline?: ModuleHeadline;
  largeHeadline?: LargeHeadline;
  sub?: ModuleSubheadline;
  text?: ModuleText;
  layout?: Layout;
  padding?: Padding;
  ctas?: CallToActions;
  image?: Image;
  textAlign?: TextAlignment;
}
/**
 * Image displayed alongside the text content
 */
export interface Image {
  source?: ImageSource;
  ratio?: ImageAspectRatio;
  alt?: AltText;
}
