/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {ButtonsProps} from "../buttons/ButtonsProps";

/**
 * Headline for the module element
 */
export type ModuleHeadline = string;
/**
 * Make the headline larger
 */
export type LargeHeadline = boolean;
/**
 * Subheadline below the module headline
 */
export type ModuleSubheadline = string;
/**
 * Info text for the module element
 */
export type ModuleText = string;
/**
 * Choose the layout for the component
 */
export type Layout = "textLeft" | "imageLeft";
/**
 * Give the component padding
 */
export type Padding = boolean;
/**
 * Image source to use
 */
export type ImageSource = string;
/**
 * Select an aspect ratio to use for cropping and displaying the image
 */
export type ImageAspectRatio = "4:3" | "3:2" | "16:9" | "1:1" | "none";
/**
 * Image description
 */
export type AltText = string;
/**
 * Choose the alginment of the text
 */
export type TextAlignment = "left" | "center";

export interface ImageStoryProps {
  headline?: ModuleHeadline;
  largeHeadline?: LargeHeadline;
  sub?: ModuleSubheadline;
  text?: ModuleText;
  layout?: Layout;
  padding?: Padding;
  /**
   * Referenced component ButtonsProps
   */
  buttons?: ButtonsProps;
  image?: Image;
  textAlign?: TextAlignment;
}
/**
 * Image displayed alongside the text content
 */
export interface Image {
  src?: ImageSource;
  ratio?: ImageAspectRatio;
  alt?: AltText;
}
