/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The URL of the logo image
 */
export type URL = string;
/**
 * The alt text of the logo
 */
export type Caption = string;

/**
 * Logo entry for Logos component
 */
export interface LogoProps {
  src: URL;
  alt?: Caption;
}
