/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of the author
 */
export type Name = string;
/**
 * The byline of the author
 */
export type Byline = string;
/**
 * URL of the image to display
 */
export type ImageSource = string;
/**
 * Alt text of the image
 */
export type AltText = string;
/**
 * Image uses all the horizontal space vailable
 */
export type FullWidth = boolean;
/**
 * Aspect Ratio of the Images
 */
export type AspectRatio = "wide" | "square" | "vertical";
/**
 * Open link in new Tab
 */
export type OpenLinkInNewTab = boolean;

/**
 * The author of the blog post
 */
export interface BlogAuthorProps {
  name: Name;
  byline?: Byline;
  image?: {
    src?: ImageSource;
    alt?: AltText;
    fullWidth?: FullWidth;
    aspectRatio?: AspectRatio;
  };
  links?: {
    icon?: string;
    label?: string;
    href?: string;
    newTab?: OpenLinkInNewTab;
  }[];
}
