declare module "@kickstartds/content/lib/count-up/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {IconProps} from "@kickstartds/base/lib/icon/typing";
import type {ButtonProps} from "@kickstartds/base/lib/button/typing";

/**
 * Final number to count to
 */
export type Number = number;
/**
 * Text prepended to the number
 */
export type Prefix = string;
/**
 * Text appended to the number
 */
export type Suffix = string;
/**
 * Topic for the count-up box. Displayed before the text, in bold
 */
export type Topic = string;
/**
 * Copy text for the element
 */
export type TextContent = string;
export type Link = {
  enabled?: DisplayLink;
  [k: string]: unknown;
} & ButtonProps;
/**
 * Toggles visibility of the link
 */
export type DisplayLink = boolean;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Component to to increase a number up to a final value
 */
export interface CountUpProps {
  to: Number;
  prefix?: Prefix;
  suffix?: Suffix;
  /**
   * Referenced component IconProps
   */
  icon?: IconProps;
  topic?: Topic;
  text?: TextContent;
  link?: Link;
  className?: Class;
  /**
   * See https://github.com/aFarkas/lazysizes/blob/gh-pages/README.md#data-expand-attribute
   */
  expand?: number;
  component?: KsComponentAttribute;
}

}
      