declare module "@kickstartds/content/lib/count-up/typing" {
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  import type { IconProps } from "@kickstartds/base/lib/icon/typing";

  /**
   * Final number to count to
   */
  export type Number = number;
  /**
   * Topic for the count-up box. Displayed before the text, in bold
   */
  export type Topic = string;
  /**
   * Copy text for the element
   */
  export type TextContent = string;
  /**
   * Text content to display inside the button
   */
  export type Label = string;
  /**
   * Target that should be linked, makes the button behave like a link semantically
   */
  export type Target = string;
  /**
   * Variant of button to be used
   */
  export type Variant = "primary" | "secondary" | "tertiary";
  /**
   * Choose an icon
   */
  export type Icon = string;
  /**
   * Size of button to use
   */
  export type Size = "small" | "medium" | "large";
  /**
   * Whether the button should be disabled
   */
  export type Disabled = boolean;
  /**
   * Toggles visibility of the link
   */
  export type DisplayLink = boolean;
  /**
   * Additional css classes attached to the wrapping element
   */
  export type Class = string;
  /**
   * Optional custom component identifier
   */
  export type KsComponentAttribute = string;

  /**
   * Component to to increase a number up to a final value
   */
  export interface CountUpProps {
    to: Number;
    /**
     * Referenced component Icon
     */
    icon?: IconProps;
    topic?: Topic;
    text?: TextContent;
    link?: Button;
    className?: Class;
    /**
     * See https://github.com/aFarkas/lazysizes/blob/gh-pages/README.md#data-expand-attribute
     */
    expand?: number;
    component?: KsComponentAttribute;
  }
  /**
   * Component used for user interaction
   */
  export interface Button {
    label: Label;
    target?: Target;
    variant?: Variant;
    icon?: Icon;
    size?: Size;
    disabled?: Disabled;
    enabled?: DisplayLink;
  }
}
