declare module "@kickstartds/base/lib/html/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HTMLString = string;
export type ShowHTMLAfterConsent = boolean;
/**
 * Add additional css classes that should be applied to the element
 */
export type AdditionalClasses = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Display raw HTML.
 */
export interface HtmlProps {
  html?: HTMLString;
  consent?: ShowHTMLAfterConsent;
  consentText?: string;
  consentButtonLabel?: string;
  consentBackgroundImage?: string;
  consentAspectRatio?: "16:9" | "16:10" | "4:3" | "1:1";
  className?: AdditionalClasses;
  component?: KsComponentAttribute;
}

}
      