declare module "@kickstartds/blog/lib/post-aside/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {PictureProps} from "./PictureProps";
import type {PostMetaProps} from "./PostMetaProps";
import type {PostShareBarProps} from "./PostShareBarProps";

/**
 * Text content for the headline
 */
export type Text = string;
/**
 * Name, company name, etc.
 */
export type Title = string;
/**
 * Position, profession, department, location, etc.
 */
export type Subtitle = string;
/**
 * Open link in new Tab
 */
export type OpenLinkInNewTab = boolean;
export type CopyText = string;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class1 = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute1 = string;

/**
 * Post Aside
 */
export interface PostAsideProps {
  author?: Contact;
  /**
   * Referenced component PostMeta
   */
  meta?: PostMetaProps;
  /**
   * Referenced component PostShareBar
   */
  shareBar?: PostShareBarProps;
  className?: Class1;
  component?: KsComponentAttribute1;
}
/**
 * Component to show contact information
 */
export interface Contact {
  headline?: Text;
  /**
   * Referenced component Picture
   */
  image?: PictureProps;
  title?: Title;
  subtitle?: Subtitle;
  links?: {
    icon?: string;
    label?: string;
    href?: string;
    newTab?: OpenLinkInNewTab;
  }[];
  copy?: CopyText;
  className?: Class;
  component?: KsComponentAttribute;
}

}
    