declare module "@kickstartds/blog/lib/post-aside/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {ContactProps} from "@kickstartds/base/lib/contact/typing";
import type {HeadlineProps} from "@kickstartds/base/lib/headline/typing";
import type {PostMetaProps} from "@kickstartds/blog/lib/post-meta/typing";
import type {PostShareBarProps} from "@kickstartds/blog/lib/post-share-bar/typing";

export type Author = ContactProps & {
  headline?: {
    [k: string]: unknown;
  } & HeadlineProps;
};
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Post Aside
 */
export interface PostAsideProps {
  author?: Author;
  /**
   * Referenced component PostMetaProps
   */
  meta?: PostMetaProps;
  /**
   * Referenced component PostShareBarProps
   */
  shareBar?: PostShareBarProps;
  className?: Class;
  component?: KsComponentAttribute;
}

}
      