declare module "@kickstartds/blog/lib/post-share-bar/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {HeadlineProps} from "@kickstartds/base/lib/headline/typing";

/**
 * Open link in new Tab
 */
export type OpenLinkInNewTab = boolean;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * Post Share Bar
 */
export interface PostShareBarProps {
  headline?: {
    content?: string & HeadlineProps;
    spaceAfter?: string & HeadlineProps;
  } & HeadlineProps;
  links?: ShareLink[];
  className?: Class;
  component?: KsComponentAttribute;
}
export interface ShareLink {
  href?: string;
  icon?: string;
  title?: string;
  newTab?: OpenLinkInNewTab;
}

}
      