declare module "@kickstartds/base/lib/section/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {HeroProps} from "@kickstartds/hero.schema.json/lib/hero/typing";
import type {CtaProps} from "@kickstartds/cta.schema.json/lib/cta/typing";
import type {MosaicProps} from "@kickstartds/mosaic.schema.json/lib/mosaic/typing";
import type {CtaPaidProps} from "@kickstartds/cta-paid.schema.json/lib/cta-paid/typing";
import type {FaqProps} from "@kickstartds/faq.schema.json/lib/faq/typing";
import type {FeaturesProps} from "@kickstartds/features.schema.json/lib/features/typing";
import type {GalleryProps} from "@kickstartds/gallery.schema.json/lib/gallery/typing";
import type {HeadlineProps} from "@kickstartds/base/lib/headline/typing";
import type {ImageStoryProps} from "@kickstartds/image-story.schema.json/lib/image-story/typing";
import type {SplitProps} from "@kickstartds/split.schema.json/lib/split/typing";
import type {StatsProps} from "@kickstartds/stats.schema.json/lib/stats/typing";
import type {StatsPaidProps} from "@kickstartds/stats-paid.schema.json/lib/stats-paid/typing";
import type {TeaserCardProps} from "@kickstartds/teaser-card.schema.json/lib/teaser-card/typing";
import type {TestimonialsProps} from "@kickstartds/testimonials.schema.json/lib/testimonials/typing";
import type {TestimonialsPaidProps} from "@kickstartds/testimonials-paid.schema.json/lib/testimonials-paid/typing";
import type {TextProps} from "@kickstartds/text.schema.json/lib/text/typing";
import type {VideoCurtainProps} from "@kickstartds/video-curtain.schema.json/lib/video-curtain/typing";
import type {ImageTextProps} from "@kickstartds/image-text.schema.json/lib/image-text/typing";
import type {LogosProps} from "@kickstartds/logos.schema.json/lib/logos/typing";
import type {LogosPaidProps} from "@kickstartds/logos-paid.schema.json/lib/logos-paid/typing";
import type {ButtonsProps} from "@kickstartds/buttons.schema.json/lib/buttons/typing";

/**
 * Width of section to use
 */
export type Width = "full" | "max" | "wide" | "default" | "narrow";
/**
 * Style of background
 */
export type Style =
  | "default"
  | "accent"
  | "bold"
  | "stagelights"
  | "horizontalGradient"
  | "verticalGradient"
  | "accentTransition"
  | "boldTransition"
  | "glow";
/**
 * Amount of spacing before the section
 */
export type SpaceBefore = "default" | "small" | "none";
/**
 * Amount of spacing after the section
 */
export type SpaceAfter = "default" | "small" | "none";
/**
 * Whether to invert the section
 */
export type Inverted = boolean;
/**
 * Headline Text for the section
 */
export type Headline = string;
/**
 * Make the headline larger
 */
export type LargeHeadline = boolean;
/**
 * Width of headline to use
 */
export type HeadlineWidth = "unset" | "narrow" | "default" | "wide";
/**
 * Choose the text alignment for the headline
 */
export type HeadlineTextAlignment = "left" | "center" | "right";
/**
 * Choose an alignment for positioning the headline
 */
export type HeadlineAlignment = "left" | "center" | "right";
/**
 * Subheadline for the section
 */
export type Subheadline = string;
/**
 * Switch the order of headline and subheadline
 */
export type SwitchHeadlineOrder = boolean;
/**
 * Width of content to use
 */
export type ContentWidth = "unset" | "narrow" | "default" | "wide";
/**
 * Choose an alignment for the content
 */
export type ContentAlignment = "left" | "center" | "right";
/**
 * Size of gutter to use
 */
export type Gutter = "large" | "default" | "small" | "none";
/**
 * Layout mode used for section contents
 */
export type Mode = "default" | "tile" | "list";
/**
 * Allowed components for content
 */
export type Content = (
  | HeroProps
  | CtaProps
  | MosaicProps
  | CtaPaidProps
  | FaqProps
  | FeaturesProps
  | GalleryProps
  | HeadlineProps
  | ImageStoryProps
  | SplitProps
  | StatsProps
  | StatsPaidProps
  | TeaserCardProps
  | TestimonialsProps
  | TestimonialsPaidProps
  | TextProps
  | VideoCurtainProps
  | ImageTextProps
  | LogosProps
  | LogosPaidProps
)[];

/**
 * Component used to layout components into pages
 */
export interface SectionProps {
  width?: Width;
  style?: Style;
  spaceBefore?: SpaceBefore;
  spaceAfter?: SpaceAfter;
  inverted?: Inverted;
  headline?: {
    text?: Headline;
    large?: LargeHeadline;
    width?: HeadlineWidth;
    textAlign?: HeadlineTextAlignment;
    align?: HeadlineAlignment;
    sub?: Subheadline;
    switchOrder?: SwitchHeadlineOrder;
  };
  content?: {
    width?: ContentWidth;
    align?: ContentAlignment;
    gutter?: Gutter;
    mode?: Mode;
  };
  components?: Content;
  /**
   * Referenced component ButtonsProps
   */
  buttons?: ButtonsProps;
}

}
      