declare module "@kickstartds/content/lib/slider/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Automatically move to next slide after 4 seconds without user interaction
 */
export type AutoPlay = boolean;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type Component = string;
/**
 * Add arrows on the left and right to navigate to next or previous slide
 */
export type ShowArrows = boolean;
/**
 * Title for left button
 */
export type ArrowPrevTitle = string;
/**
 * Icon identifier for left button
 */
export type ArrowPrevIcon = string;
/**
 * Title for right button
 */
export type ArrowNextTitle = string;
/**
 * Icon identifier for right button
 */
export type ArrowNextIcon = string;
/**
 * Add bullet navigation
 */
export type ShowNavigation = boolean;
/**
 * Prop name to use for bullet nav title
 */
export type NavigationTitleProp = string;
/**
 * Disable dragging slides with mouse or touch
 */
export type DisableDragging = boolean;
export type TeaseNeighbourSlides = boolean;
export type EqualizeSlidesHeights = boolean;
/**
 * Size of the gap added between slides in pixels
 */
export type Gap = number;
/**
 * Type of the movement
 */
export type Type = "slider" | "carousel";

/**
 * Slider
 */
export interface SliderProps {
  autoplay?: AutoPlay;
  className?: Class;
  component?: Component;
  arrows?: ShowArrows;
  arrowPrefTitle?: ArrowPrevTitle;
  arrowPrevIcon?: ArrowPrevIcon;
  arrowNextTitle?: ArrowNextTitle;
  arrowNextIcon?: ArrowNextIcon;
  nav?: ShowNavigation;
  navTitleProp?: NavigationTitleProp;
  disableDragging?: DisableDragging;
  teaseNeighbours?: TeaseNeighbourSlides;
  equalHeight?: EqualizeSlidesHeights;
  gap?: Gap;
  type?: Type;
}

}
      