/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Picture source
 */
export type Source = string;
/**
 * Picture source
 */
export type Source1 = string;
/**
 * Alt text to display for picture
 */
export type AltText = string;
/**
 * Width of the picture
 */
export type Width = number;
/**
 * Height of the picture
 */
export type Height = number;
/**
 * Toggle the inversion of the flyout navigation
 */
export type FlyoutInverted = boolean;
/**
 * Toggle the inversion of the dropdown navigation
 */
export type DropdownInverted = boolean;
/**
 * Make the header float over the first Section
 */
export type Floating = boolean;
/**
 * Invert the color scheme of the header
 */
export type Inverted = boolean;

/**
 * Header layered on top by the CMS
 */
export interface HeaderProps {
  logo?: Logo;
  flyoutInverted?: FlyoutInverted;
  dropdownInverted?: DropdownInverted;
  floating?: Floating;
  inverted?: Inverted;
  navItems?: {
    href: string;
    label: string;
    active?: boolean;
  }[];
}
export interface Logo {
  src?: Source;
  srcInverted?: Source1;
  alt?: AltText;
  homepageHref?: string;
  width?: Width;
  height?: Height;
}
