/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {BlogTagProps} from "../blog-tag/BlogTagProps";

/**
 * The date of the blog post
 */
export type Date = string;
/**
 * The tags for the blog post
 */
export type Tags = BlogTagProps[];
/**
 * The headline of the blog post
 */
export type Headline = string;
/**
 * The teaser text of the blog post
 */
export type TeaserText = string;
/**
 * The preview image for the blog post
 */
export type Image = string;
/**
 * The alt text for the preview image
 */
export type Alt = string;
/**
 * The blog entry URL to link
 */
export type URL = string;
/**
 * The text for the link
 */
export type Text = string;
/**
 * Time to read for the blog post
 */
export type ReadingTime = string;
/**
 * The name of the author
 */
export type Name = string;
/**
 * The title of the author
 */
export type Title = string;
/**
 * The image URL of the author
 */
export type Image1 = string;

/**
 * Display a blog teaser with date, tags, headline, teaser text and author
 */
export interface BlogTeaserProps {
  date?: Date;
  tags?: Tags;
  headline: Headline;
  teaserText: TeaserText;
  image?: Image;
  alt?: Alt;
  link?: Link;
  readingTime?: ReadingTime;
  author?: Author;
  className?: string;
}
/**
 * URL and label for the blog post linked
 */
export interface Link {
  url: URL;
  text?: Text;
}
/**
 * The author of the blog post
 */
export interface Author {
  name: Name;
  title?: Title;
  image?: Image1;
}
