/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Headline for the gallery
 */
export type Headline = string;
/**
 * Text for the gallery
 */
export type Text = string;
/**
 * The images to display in the gallery
 *
 * @minItems 1
 * @maxItems 10
 */
export type Images =
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ];
/**
 * The URL of the image
 */
export type URL = string;
/**
 * The caption of the image
 */
export type Caption = string;
/**
 * The alignment gallery images
 */
export type Align = "stack" | "smallTiles" | "largeTiles";

/**
 * Component used to display a gallery of images
 */
export interface GalleryProps {
  headline?: Headline;
  text?: Text;
  images: Images;
  align?: Align;
  [k: string]: unknown;
}
