/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * The images to display in the gallery
 *
 * @minItems 1
 * @maxItems 10
 */
export type Images =
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ]
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ]
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ]
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ]
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ]
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ]
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ]
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ]
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ]
  | [
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      },
      {
        url: URL;
        alt?: AltText;
        caption?: Caption;
      }
    ];
/**
 * The URL of the image
 */
export type URL = string;
/**
 * Alt text of the image
 */
export type AltText = string;
/**
 * The caption of the image
 */
export type Caption = string;
/**
 * The layout of the gallery images
 */
export type Layout = "stack" | "smallTiles" | "largeTiles";

/**
 * Component used to display a gallery of images
 */
export interface GalleryProps {
  images: Images;
  layout?: Layout;
}
