/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {BlogTeaserProps} from "../blog-teaser/BlogTeaserProps";
import type {CtaProps} from "../cta/CtaProps";
import type {SeoProps} from "../seo/SeoProps";

/**
 * Collection of posts to list on the page
 */
export type Posts = BlogTeaserProps[];
/**
 * Collection of posts to list on the page
 */
export type Posts1 = BlogTeaserProps[];

/**
 * Abstracts a blog overview concept into JSON schema
 */
export interface BlogOverviewProps {
  /**
   * Referenced component BlogTeaserProps
   */
  latest?: BlogTeaserProps;
  list?: Posts;
  more?: Posts1;
  /**
   * Referenced component CtaProps
   */
  cta?: CtaProps;
  /**
   * Referenced component SeoProps
   */
  seo: SeoProps;
}
