/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {BlogHeadProps} from "../blog-head/BlogHeadProps";
import type {BlogAsideProps} from "../blog-aside/BlogAsideProps";
import type {CtaProps} from "../cta/CtaProps";
import type {SeoProps} from "../seo/SeoProps";

/**
 * Body text for the blog post
 */
export type Text = string;

/**
 * Abstracts a blog post concept into JSON schema
 */
export interface BlogPostProps {
  /**
   * Referenced component BlogHeadProps
   */
  head?: BlogHeadProps;
  /**
   * Referenced component BlogAsideProps
   */
  aside?: BlogAsideProps;
  content?: Text;
  /**
   * Referenced component CtaProps
   */
  cta?: CtaProps;
  /**
   * Referenced component SeoProps
   */
  seo: SeoProps;
}
