/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {SectionProps} from "../section/SectionProps";
import type {SeoProps} from "../seo/SeoProps";

/**
 * Collection of sections (with their contents) to render on the page
 */
export type Sections = SectionProps[];
/**
 * Toggle default floating header behaviour set in global settings
 */
export type ToggleFloating = boolean;
/**
 * Toggle default inverted header behaviour set in global settings
 */
export type ToggleInverted = boolean;
/**
 * Toggle default inverted footer behaviour set in global settings
 */
export type ToggleInverted1 = boolean;

/**
 * Abstracts a page concept into JSON schema
 */
export interface PageProps {
  section?: Sections;
  header?: Header;
  footer?: Footer;
  /**
   * Referenced component SeoProps
   */
  seo: SeoProps;
}
/**
 * Header settings for the page
 */
export interface Header {
  floating?: ToggleFloating;
  inverted?: ToggleInverted;
}
/**
 * Footer settings for the page
 */
export interface Footer {
  inverted?: ToggleInverted1;
}
