/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {SectionProps} from "../section/SectionProps";
import type {SeoProps} from "../seo/SeoProps";

/**
 * Collection of sections (with their contents) to render on the page
 */
export type Sections = SectionProps[];

/**
 * Abstracts a page concept into JSON schema
 */
export interface PageProps {
  section?: Sections;
  /**
   * Referenced component SeoProps
   */
  seo: SeoProps;
}
