/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Headline for the section
 */
export type Headline = string;
/**
 * Subheadline for the section
 */
export type Subheadline = string;
/**
 * Switch the order of headline and subheadline
 */
export type SwitchHeadlineOrder = boolean;
/**
 * Width of section to use
 */
export type Width = "full" | "max" | "wide" | "default" | "narrow";
/**
 * Size of gutter to use
 */
export type Gutter = "large" | "default" | "small" | "none";
/**
 * Layout mode used for section contents
 */
export type Mode = "default" | "tile" | "list";
/**
 * Alignment for the section headline and cta's
 */
export type Alignment = "left" | "center";
/**
 * Text content to display inside the button
 */
export type Label = string;
/**
 * Target that should be linked, makes the button behave like a link semantically
 */
export type Target = string;
/**
 * Variant of button to be used
 */
export type Variant = "primary" | "secondary" | "tertiary";
/**
 * Choose an icon
 */
export type Icon = string;
/**
 * Size of button to use
 */
export type Size = "small" | "medium" | "large";
/**
 * Whether the button should be disabled
 */
export type Disabled = boolean;
/**
 * Text content of headline
 */
export type Text = string;
/**
 * Subheadline content
 */
export type Sub = string;
/**
 * Switch order of headline and subheadline
 */
export type SwitchOrder = boolean;
export type SectionAlignment = "left" | "center" | "right";
/**
 * Level of headline to use
 */
export type Level = "h1" | "h2" | "h3" | "h4" | "p";
/**
 * Style of headline to show
 */
export type Style = "h1" | "h2" | "h3" | "h4" | "p";
/**
 * Whether to display space after headline
 */
export type SpaceAfter = "minimum" | "small" | "large";
/**
 * Set a custom class name
 */
export type ClassName = string;
/**
 * Headline for the teaser card
 */
export type Headline2 = string;
/**
 * Body text for the teaser card
 */
export type Text1 = string;
/**
 * Target that should be linked
 */
export type Target1 = string;
/**
 * Image to display as cover
 */
export type Image = string;
/**
 * Whether to invert the card
 */
export type InvertCard = boolean;
/**
 * Allowed content for the section
 */
export type Content = (Button | Headline1 | TeaserCard)[];
/**
 * Style of background
 */
export type Style1 = "default" | "accent" | "bold";
/**
 * Amount of spacing before the section
 */
export type SpaceBefore = "default" | "small" | "none";
/**
 * Amount of spacing after the section
 */
export type SpaceAfter1 = "default" | "small" | "none";
/**
 * Whether to invert the section
 */
export type Inverted = boolean;
/**
 * Label for the Call to action
 */
export type Label1 = string;
/**
 * Target for the Call to action
 */
export type Target2 = string;
/**
 * Add Call to actions to the end of the section
 */
export type CallToActions = {
  label: Label1;
  target: Target2;
}[];

/**
 * Component used to layout components into pages
 */
export interface SectionProps {
  headline?: Headline;
  sub?: Subheadline;
  switchHeadlineOrder?: SwitchHeadlineOrder;
  width?: Width;
  gutter?: Gutter;
  mode?: Mode;
  align?: Alignment;
  content?: Content;
  style?: Style1;
  spaceBefore?: SpaceBefore;
  spaceAfter?: SpaceAfter1;
  inverted?: Inverted;
  ctas?: CallToActions;
}
/**
 * Component used for user interaction
 */
export interface Button {
  label: Label;
  target?: Target;
  variant?: Variant;
  icon?: Icon;
  size?: Size;
  disabled?: Disabled;
}
/**
 * Component used for headlines
 */
export interface Headline1 {
  text: Text;
  sub?: Sub;
  switchOrder?: SwitchOrder;
  align?: SectionAlignment;
  level: Level;
  style?: Style;
  spaceAfter?: SpaceAfter;
  className?: ClassName;
}
/**
 * Component used to tease content
 */
export interface TeaserCard {
  headline?: Headline2;
  text?: Text1;
  target?: Target1;
  image?: Image;
  inverted?: InvertCard;
}
