/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Headline for the logos
 */
export type Headline = string;
/**
 * The alignment of the headline
 */
export type HeadlineAlign = "left" | "center" | "right";
/**
 * The logos to display
 *
 * @minItems 1
 * @maxItems 20
 */
export type Logos =
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ]
  | [
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      },
      {
        url: URL;
        caption?: Caption;
        [k: string]: unknown;
      }
    ];
/**
 * The URL of the logo image
 */
export type URL = string;
/**
 * The caption of the logo image
 */
export type Caption = string;
/**
 * The amount of logos to display per row
 */
export type LogosPerRow = number;
/**
 * The call to action text
 */
export type CallToActionText = string;

/**
 * Component used to display a set of logos
 */
export interface LogosProps {
  headline?: Headline;
  headlineAlign?: HeadlineAlign;
  logos: Logos;
  logosPerRow?: LogosPerRow;
  ctaText?: CallToActionText;
  [k: string]: unknown;
}
