/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The layout variant to use for the features
 */
export type Layout = "largeTiles" | "smallTiles" | "list";
/**
 * Activate/disable the CTAs
 */
export type CTAToggle = boolean;
/**
 * The features to display
 *
 * @minItems 1
 * @maxItems 8
 */
export type Features =
  | [Feature]
  | [Feature, Feature]
  | [Feature, Feature, Feature]
  | [Feature, Feature, Feature, Feature]
  | [Feature, Feature, Feature, Feature, Feature]
  | [Feature, Feature, Feature, Feature, Feature, Feature]
  | [Feature, Feature, Feature, Feature, Feature, Feature, Feature]
  | [Feature, Feature, Feature, Feature, Feature, Feature, Feature, Feature];
/**
 * The icon for the feature
 */
export type Icon = string;
/**
 * The title of the feature
 */
export type Title = string;
/**
 * The description of the feature
 */
export type Text = string;
/**
 * The CTA target
 */
export type CallToActionTarget = string;
/**
 * The text label displayed on the link
 */
export type LinkLabel = string;

/**
 * Component used to display a set of features
 */
export interface FeaturesProps {
  layout?: Layout;
  style?: "intext" | "stack" | "centered" | "besideLarge" | "besideSmall";
  ctas?: {
    toggle?: CTAToggle;
    style?: "button" | "link" | "intext";
  };
  feature?: Features;
}
export interface Feature {
  icon?: Icon;
  title: Title;
  text?: Text;
  cta?: CallToAction;
}
/**
 * The call to action
 */
export interface CallToAction {
  target?: CallToActionTarget;
  label?: LinkLabel;
}
