/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {FeatureProps} from "../feature/FeatureProps";

/**
 * The layout variant to use for the features
 */
export type Layout = "largeTiles" | "smallTiles" | "list";
/**
 * Activate/disable the CTAs
 */
export type CTAToggle = boolean;
/**
 * The features to display
 *
 * @minItems 1
 * @maxItems 8
 */
export type Features =
  | [FeatureProps]
  | [FeatureProps, FeatureProps]
  | [FeatureProps, FeatureProps, FeatureProps]
  | [FeatureProps, FeatureProps, FeatureProps, FeatureProps]
  | [FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps]
  | [FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps]
  | [FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps]
  | [FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps, FeatureProps];

/**
 * Component used to display a set of features
 */
export interface FeaturesProps {
  layout?: Layout;
  style?: "intext" | "stack" | "centered" | "besideLarge" | "besideSmall";
  ctas?: {
    toggle?: CTAToggle;
    style?: "button" | "link" | "intext";
  };
  feature?: Features;
}
