/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Picture source
 */
export type Source = string;
/**
 * Alt text to display for picture
 */
export type AltText = string;
/**
 * Width of the picture
 */
export type Width = number;
/**
 * Height of the picture
 */
export type Height = number;

export interface FooterProps {
  logo: Logo;
  logoHref?: string;
  navItems?: {
    href: string;
    label: string;
    target?: string;
  }[];
}
export interface Logo {
  src?: Source;
  alt?: AltText;
  width?: Width;
  height?: Height;
}
