/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {TestimonialProps} from "../testimonial/TestimonialProps";

/**
 * Add testimonials featuring an image, a quote, a source and a rating
 */
export type Testimonials = TestimonialProps[];

/**
 * Display testimonials with an optional image and rating
 */
export interface TestimonialsProps {
  testimonial?: Testimonials;
}
