/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * The testimonial quote
 */
export type Quote = string;
/**
 * The name of the quote author
 */
export type Name = string;
/**
 * The title of the quote author
 */
export type Title = string;
/**
 * The image to display with the testimonial
 */
export type Image = string;
/**
 * The rating of the testimonial, from 1 to 5
 */
export type Rating = number;

/**
 * Display a testimonial with an optional image and rating
 */
export interface TestimonialProps {
  quote: Quote;
  name?: Name;
  title?: Title;
  image?: Image;
  rating?: Rating;
}
