/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {PictureProps} from "@kickstartds/base/lib/picture/typing";

export interface NavMainProps {
  /**
   * Referenced component PictureProps
   */
  logo: PictureProps;
  logoHref?: string;
  items?: {
    href: string;
    label: string;
    active?: boolean;
  }[];
}
