/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The value of the stat
 */
export type Value = string;
/**
 * The icon of the stat
 */
export type Icon = string;
/**
 * The label of the stat
 */
export type Label = string;
/**
 * The description of the stat
 */
export type Label1 = string;
/**
 * The stats to display in a grid
 */
export type Stats = Stat[];

/**
 * Display a set of stats in a grid
 */
export interface StatsProps {
  stats: Stats;
}
export interface Stat {
  value: Value;
  icon?: Icon;
  label: Label;
  description?: Label1;
}
