/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * The value of the stat
 */
export type Value = number;
/**
 * The icon of the stat
 */
export type Icon = string;
/**
 * The label of the stat
 */
export type Label = string;
/**
 * The stats to display in a grid
 */
export type Stats = Stat[];

/**
 * Display a set of stats in a grid
 */
export interface StatsProps {
  stats: Stats;
  [k: string]: unknown;
}
export interface Stat {
  value: Value;
  icon?: Icon;
  label?: Label;
  [k: string]: unknown;
}
