/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The stats to display in a grid
 *
 * @minItems 1
 * @maxItems 4
 */
export type Stats = [Stat] | [Stat, Stat] | [Stat, Stat, Stat] | [Stat, Stat, Stat, Stat];
/**
 * The number of the stat
 */
export type Number = string;
/**
 * Optional description of the stat
 */
export type Description = string;
/**
 * Title of the stat
 */
export type Title = string;

/**
 * Display a set of stats in a grid
 */
export interface StatsProps {
  stats: Stats;
}
export interface Stat {
  number: Number;
  description?: Description;
  title?: Title;
}
