/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Headline for the visual
 */
export type Headline = string;
/**
 * Subheadline below the module headline
 */
export type ModuleSubheadline = string;
/**
 * Info text for the module element
 */
export type ModuleText = string;
/**
 * Visually highlight the text
 */
export type HighlightText = boolean;
/**
 * Make the text and buttons color neutral
 */
export type ColorNeutral = boolean;
/**
 * Text content to display inside the button
 */
export type Label = string;
/**
 * Choose an icon
 */
export type Icon = string;
/**
 * Target that should be linked, makes the button behave like a link semantically
 */
export type Target = string;
/**
 * Enable grid layer
 */
export type GridLayer = boolean;
/**
 * Background video source for small screens
 */
export type MobileVideoSource = string;
/**
 * Background video source for medium screens
 */
export type TabletVideoSource = string;
/**
 * Background video source for large screens
 */
export type DesktopVideoSource = string;
/**
 * Choose the alginment of the module content
 */
export type ModuleAligment = "center" | "left" | "right";

export interface VideoCurtainProps {
  headline?: Headline;
  sub?: ModuleSubheadline;
  text?: ModuleText;
  highlightText?: HighlightText;
  colorNeutral?: ColorNeutral;
  buttons?: Button[];
  overlay?: GridLayer;
  video?: BackgroundVideo;
  textPosition?: ModuleAligment;
}
export interface Button {
  label?: Label;
  icon?: Icon;
  target?: Target;
}
/**
 * Sources of background videos for different screen sizes
 */
export interface BackgroundVideo {
  srcMobile: MobileVideoSource;
  srcTablet?: TabletVideoSource;
  srcDesktop?: DesktopVideoSource;
}
