/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {ButtonProps} from "../button/ButtonProps";

/**
 * Headline for the visual
 */
export type Headline = string;
/**
 * Boolean to set if the headline is supposed to resemble a h1 headline at the start of the page
 */
export type LargeHeadline = boolean;
/**
 * Subheadline below the module headline
 */
export type ModuleSubheadline = string;
/**
 * Info text for the module element
 */
export type ModuleText = string;
/**
 * Visually highlight the text
 */
export type HighlightText = boolean;
/**
 * Buttons of the Button Group
 */
export type Buttons = ButtonProps[];
/**
 * Enable grid layer
 */
export type GridLayer = boolean;
/**
 * Background video source for small screens
 */
export type MobileVideoSource = string;
/**
 * Background video source for medium screens
 */
export type TabletVideoSource = string;
/**
 * Background video source for large screens
 */
export type DesktopVideoSource = string;
/**
 * Choose the alginment of the module content
 */
export type ModuleAligment = "center" | "left" | "right";

export interface VideoCurtainProps {
  headline?: Headline;
  largeHeadline?: LargeHeadline;
  sub?: ModuleSubheadline;
  text?: ModuleText;
  highlightText?: HighlightText;
  buttons?: Buttons;
  overlay?: GridLayer;
  video?: BackgroundVideo;
  textPosition?: ModuleAligment;
}
/**
 * Sources of background videos for different screen sizes
 */
export interface BackgroundVideo {
  srcMobile: MobileVideoSource;
  srcTablet?: TabletVideoSource;
  srcDesktop?: DesktopVideoSource;
}
